let container=document.querySelector('#container');
let para=document.createElement('p');
para.textContent="Hey i am red";
para.style.color='red';
container.appendChild(para);
let h3tag=document.createElement('h3');
h3tag.style.color='blue';
h3tag.textContent='i am a blue h3';
container.appendChild(h3tag);
let divChild=document.createElement('div');
divChild.style.cssText='background:pink;border:solid-black;';
container.appendChild(divChild);
let h1=document.createElement('h1');
h1.textContent='Im in a Div';
h1.style.cssText="background-color:pink;border:solid black";
divChild.appendChild(h1);
let para2=document.createElement('p');
para2.textContent="Me too!";
divChild.appendChild(para2);